name: flutter_f6sny
description: to make you laugh a little
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  timeago: ^3.3.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_localizations: 
    sdk: flutter
  intl: any
  share_plus: ^6.3.4
  namefully: ^0.2.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app-icons/AppStore-1024@1x.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/splash/

